latex-papersize.zip: README ../latex-papersize.py
	mkdir -p latex-papersize
	cp $^ latex-papersize/
	zip -9r latex-papersize.zip latex-papersize
	rm -r latex-papersize
	@echo "Use CTAN upload, latex-papersize.zip, CTAN location: /support/latex-papersize/"
